version: '3.9'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp
    container_name: myapp
    ports:
      - "${PORT}:8000"
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
